/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.20
 * Generated at: 2019-06-26 00:08:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class principalUsur_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t<title>TebFlix - Plataforma dedicada al mundo de los cómics</title>\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style_principalUsur.css\">\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery-3.4.0.min.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/script1.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jQueryRotate.js\"></script>\n");
      out.write("\t<link href=\"https://fonts.googleapis.com/css?family=Gugi|PT+Sans\" rel=\"stylesheet\"> <!--fuente-->\n");
      out.write("\t<link href=\"https://fonts.googleapis.com/css?family=Abel\" rel=\"stylesheet\">\n");
      out.write("\t<link href=\"https://fonts.googleapis.com/css?family=Source+Code+Pro\" rel=\"stylesheet\">\n");
      out.write("\t<link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"./img/favicon-16x16.png\">\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0\"/>\n");
      out.write("\t<!--<link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"./img/favicon.png\">-->\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t<div id=\"capaCubrir\"> </div>\n");
      out.write("\t<!-- Cabecera -->\n");
      out.write("\t<header>\n");
      out.write("\t\t<div id=\"titulo\">\n");
      out.write("\t\t\t<h1 class=\"titulos\"><a class=\"titulos\"href=\"#\">TebFlix</a></h1>\n");
      out.write("\t\t\t<h2>Cómics, eventos y mucho más</h2>\n");
      out.write("\t\t\t<a class=\"logo\" href=\"#\"> <img src=\"./img/logo_final1.png\" class=\"logo\"> </a>\n");
      out.write("\t\t\t<img src=\"./img/menuBlanco.png\" id=\"logoMenu\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t<div id=\"redes\">\n");
      out.write("\t\t\t\t<a href=\"https://es-es.facebook.com/\" target=\"_blank\"> <img src=\"./img/facebookblanco32.png\"\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\tid=\"facebook\"> </a>\n");
      out.write("\t\t\t\t<a href=\"https://www.youtube.com/\" target=\"_blank\"> <img src=\"./img/youtubeblanco32.png\"\n");
      out.write("\t\t\t\t\tid=\"youtube\"> </a>\n");
      out.write("\t\t\t\t<a href=\"https://twitter.com/?lang=es/\" target=\"_blank\"> <img src=\"./img/twitterblanco32.png\"\n");
      out.write("\t\t\t\t\tid=\"twitter\"> </a>\n");
      out.write("\t\t\t\t<a href=\"https://www.instagram.com/?hl=es/\" target=\"_blank\"> <img src=\"./img/instagramblanco32.png\"\n");
      out.write("\t\t\t\t\tid=\"instagram\"> </a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<a href=\"\" id=\"inisesion\">Mi Perfil</a>\n");
      out.write("\t\t\t<a href=\"\" id=\"botonRegis\">Cerrar sesión</a> \n");
      out.write("\t\t</div>\n");
      out.write("\t</header>\n");
      out.write("\n");
      out.write("\t<!-- Menú -->\n");
      out.write("\t<nav id=\"menu\">\n");
      out.write("\t\t<ul id=\"menu1\" class=\"nav\">\n");
      out.write("\t\t\t<li> <a href=\"#\"> Inicio </a></li>\n");
      out.write("\t\t\t<li id=\"sub1\"class=\"opt\"> <a href=\"categorias.jsp\"> Categorías </a>\n");
      out.write("\t\t\t\t<ul id=\"sub11\">\n");
      out.write("\t\t\t\t\t<li href=\"\" id=\"subini\"> <a href=\"\"> > Acción </a></li>\n");
      out.write("\t\t\t\t\t<li href=\"\"> <a href=\"\"> > Ciencia Ficción </a></li>\n");
      out.write("\t\t\t\t\t<li href=\"\"> <a href=\"\"> > Detectives </a></li>\n");
      out.write("\t\t\t\t\t<li href=\"\"> <a href=\"\"> > Fantasía </a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</li>\n");
      out.write("\t\t\t<li href=\"\"> <a href=\"\"> Eventos </a></li>\n");
      out.write("\t\t\t<li href=\"\"> <a href=\"\"> Tiendas de cómics </a></li>\n");
      out.write("\t\t\t<li id=\"final\" href=\"\"> <a href=\"\"> Conócenos </a></li>\n");
      out.write("\t\t</ul>\n");
      out.write("\t</nav>\n");
      out.write("\n");
      out.write("<main>\n");
      out.write("\t\n");
      out.write("\t<!-- Introducción -->\n");
      out.write("\t<div id=\"contenido\">\n");
      out.write("\t\t<section id=\"intro\">\n");
      out.write("\t\t\t<h3>Lo que siempre has deseado.</h3>\n");
      out.write("\t\t\t<p id=\"p1\">TebFlix es un nuevo portal innovador dedicado al mundo del cómic. Aquí podréis\n");
      out.write("\t\t\t\tconocer a nuevos artistas, estar al día de eventos y novedades y subir vuestro \n");
      out.write("\t\t\t\tpropio contenido con el fin de compartir vuestro talento.</p>\n");
      out.write("\t\t\t<p id=\"p2\">Si los cómics son tu pasión...</br>¡este es tu sitio!</p>\n");
      out.write("\t\t</section>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<div id=\"contenido2\">\n");
      out.write("\t\t<!-- Información: no sé qué poner, pero estaría bien meter algo de relleno en medio.-->\n");
      out.write("\t\t<section id=\"informacion\">\n");
      out.write("\t\t\t<h4>Próximos eventos</h4>\n");
      out.write("\t\t\t<div class=\"imagenes\" id=\"info1\"> \n");
      out.write("\t\t\t\t<p class=\"estilotexto\" id=\"textoinfo1\">XVII Salón del cómic en Zaragoza</p>\n");
      out.write("\t\t\t\t<img class=\"estiloimagen\" id=\"fotoinfo1\" src=\"img/comic_zaragoza.jpg\">\n");
      out.write("\t\t\t\t<p class=\"textoPrueba\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean dapibus, odio et bibendum feugiat, enim dui rutrum ligula illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. .</p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"imagenes\" id=\"info2\">\n");
      out.write("\t\t\t\t<p class=\"estilotexto\" id=\"textoinfo2\">Cómic 37 en Barcelona</p>\n");
      out.write("\t\t\t\t<img class=\"estiloimagen\" id=\"fotoinfo2\" src=\"img/comic_barcelona.jpg\">\n");
      out.write("\t\t\t\t<p class=\"textoPrueba\">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. </p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"imagenes\" id=\"info3\">\n");
      out.write("\t\t\t\t<p class=\"estilotexto\" id=\"textoinfo3\">ComiCON en Madrid</p>\n");
      out.write("\t\t\t\t<img class=\"estiloimagen\" id=\"fotoinfo3\" src=\"img/feria_comic_madrid.png\">\n");
      out.write("\t\t\t\t<p class=\"textoPrueba\">At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. </p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</section>\n");
      out.write("\n");
      out.write("\t\t<section id=\"lateral\">\n");
      out.write("\t\t\t<section id=\"infoPersonal\">\n");
      out.write("\t\t\t<p id=\"cuentaPrin\">Cuenta.</p>\n");
      out.write("\t\t\t<p><strong> Nombre: </strong></p>\n");
      out.write("\t\t\t<p><strong>Nombre de usuario: </strong></p>\n");
      out.write("\t\t\t<p><strong>Correo: </strong></p>\n");
      out.write("\t\t</section>\n");
      out.write("\t\t\t<a id=\"cuentaBoton\" href=\"Navegador\"><input type=\"button\" value=\"Mi perfil\" id=\"suscrip2\"> </a>\n");
      out.write("\t\t</section>\n");
      out.write("\n");
      out.write("\t\t<section id=\"comics\">\n");
      out.write("\t\t\t<h4>Últimos cómics subidos</h4>\n");
      out.write("\t\t</section>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("</main>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<!-- Footer -->\n");
      out.write("\t<footer id=\"pie\">\n");
      out.write("\t\t<div>\n");
      out.write("\t\t\t<a href=\"https://es-es.facebook.com/\" target=\"_blank\"> <img src=\"./img/facebookblanco32.png\"\t\t\tid=\"facebook\"> </a>\n");
      out.write("\t\t\t<a href=\"https://www.youtube.com/\" target=\"_blank\"> <img src=\"./img/youtubeblanco32.png\"\n");
      out.write("\t\t\t\tid=\"youtube\"> </a>\n");
      out.write("\t\t\t<a href=\"https://twitter.com/?lang=es/\" target=\"_blank\"> <img src=\"./img/twitterblanco32.png\"\n");
      out.write("\t\t\t\tid=\"twitter\"> </a>\n");
      out.write("\t\t\t<a href=\"https://www.instagram.com/?hl=es/\" target=\"_blank\"> <img src=\"./img/instagramblanco32.png\"\n");
      out.write("\t\t\t\tid=\"instagram\"> </a>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<ul>\n");
      out.write("\t\t\t<li><a class=\"enl\" href=\"#\">Privacidad.</a></li>\n");
      out.write("\t\t\t<li><a class=\"enl\" href=\"#\">Términos y condiciones.</a></li>\n");
      out.write("\t\t</ul>\n");
      out.write("\t\t<p id=\"copy\">Copyright 2019 ©. TebFlix.</p>\n");
      out.write("\t</footer>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\t\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
