CREATE SCHEMA `TEBFLIX` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish2_ci ;
USE TEBFLIX;

CREATE TABLE USUARIO (
	CORREO VARCHAR(50) NOT NULL,
    USUARIO VARCHAR(25) PRIMARY KEY,
    NOMBRE VARCHAR(15) NOT NULL,
    APELLIDO1 VARCHAR(15) NOT NULL,
    APELLIDO2 VARCHAR(15),
    CONTRASENA VARCHAR(12),
    PROVEEDOR BOOL
);

CREATE TABLE COMIC (
	CODIGO INT PRIMARY KEY,
    USUARIO VARCHAR(25), 
    FOREIGN KEY (USUARIO) REFERENCES USUARIO(USUARIO),
    TITULO VARCHAR(50),
    CATEGORIA VARCHAR(20),
    SINOPSIS TEXT,
    PDF VARCHAR(60),
    FECHA DATE,
    IMAGEN VARCHAR(60)
);

CREATE TABLE COMICFAV (
    ID INT PRIMARY KEY,
    USUARIO VARCHAR(25),
    CODIGO INT,
	FOREIGN KEY (USUARIO) REFERENCES USUARIO(USUARIO),
    FOREIGN KEY (CODIGO) REFERENCES COMIC(CODIGO)
);